class BoardPiece {

    /**
     * @param {string} id
     * @param {Piece} piece
     * @param {BasicStyle} style
     * @param {boolean} clickable
     * @param {boolean} droppable
     * @param {boolean} draggable
     */
    constructor({
        id,
        piece = null,
        style,
        highlightedStyle,
        dragOverStyle,
        clickable = true,
        droppable = true,
        draggable = false
    } = {}) {

        this.id = id;

        this.piece = null;

        this._highlighted = false;

        this.cloned = 0;

        this._renderer = new BoardPieceRenderer(this, {
            piece,
            style,
            highlightedStyle,
            dragOverStyle,
            clickable,
            droppable,
            draggable
        });

        if (piece) {
            this.addPiece(piece);
        }
    }

    // --- RENDERING API ---

    /**
     * Returns the HTML element representing this board piece, as generated by its renderer.
     * @returns {HTMLElement} The HTML element representing this board piece.
     */
    get el() {
        return this._renderer.el;
    }

    /**
     * Refreshes the boardPiece's display. This is called internally whenever the board state changes.
     * If changes are made to the board state outside of the provided methods, this method should be called manually to update the display.
     */
    refresh() {
        this._renderer.refresh();
    }

    /**
     * Sets the style of the board piece and refreshes its display. The style should be an instance of BasicStyle or a compatible object.
     * @param {BasicStyle} v the new style to apply to the board piece.
     */
    set style(v) {
        this._renderer.style = v;
        this.refresh();
    }

    /**
      * @returns {Style} the default style of the board piece.
     */
    get style() {
        return this._renderer.style;
    }

    /**
     * Sets the highlighted style of the board piece and refreshes its display. 
     * @param {Style} v the new highlighted style to apply to the board piece when it is highlighted.
     */
    set highlightedStyle(v) {
        this._renderer.highlightedStyle = v;
        this.refresh();
    }

    /**
     * @returns {Style} the highlighted style of the board piece.
     */
    get highlightedStyle() {
        return this._renderer.highlightedStyle;
    }

    /**
     * Sets the style to apply to the board piece when it is being dragged over, and refreshes its display.
     * @param {Style} v the new style to apply to the board piece when it is being dragged over.
     */
    set dragOverStyle(v) {
        this._renderer.dragOverStyle = v;
        this.refresh();
    }

    get dragOverStyle() {
        return this._renderer.dragOverStyle;
    }

    set clickable(v) {
        this._renderer.clickable = v;
    }

    get clickable() {
        return this._renderer.clickable;
    }

    set droppable(v) {
        this._renderer.droppable = v;
    }

    get droppable() {
        return this._renderer.droppable;
    }

    set draggable(v) {
        this._renderer.draggable = v;
    }

    get draggable() {
        return this._renderer.draggable;
    }

    set highlighted(v) {
        this._highlighted = v;
        this.refresh();
    }

    get highlighted() {
        return this._highlighted;
    }

    // --- PIECE LOGIC ---

    addPiece(piece) {

        if (this.piece) return false;

        this.piece = piece;

        piece._setBoardPiece(this);

        this.refresh();

        return true;
    }

    removePiece() {

        if (!this.piece) return false;

        this.piece._setBoardPiece(null);

        this.piece = null;

        this.refresh();

        return true;
    }

    isEmpty() {
        return this.piece === null;
    }

    // --- AUX ---

    /**
     * Clones a board piece and returns a new instance.
     * The piece property is not cloned and will be set to null in the new instance.
     * @returns {BoardPiece} A new instance of BoardPiece with the same properties as the original.
     */
    clone() {

        this.cloned++;

        return new BoardPiece({
            id: `${this.id}_clone_${this.cloned}`,
            style: this.style?.clone?.(),
            highlightedStyle: this.highlightedStyle?.clone?.(),
            dragOverStyle: this.dragOverStyle?.clone?.(),
            clickable: this.clickable,
            droppable: this.droppable,
            draggable: this.draggable
        });
    }
}